### ISSUE TITLE
Update treat to 1.4.3

### ISSUE THREAD

**Issue by Blastoplex** [maraisr/rollup-plugin-treat#2]
Hey @maraisr! 

We briefly spoke on the treat issue board, I know this isn't quite the place for introductions and conversation starters. But I wanted to flag my teams interest in this lib and see if there's any room for us to help work on this project.

We work for MYOB in Melbourne on the [Feelix design system](feelix.myob.com), and were currently looking into css in js options. Our dev team consists of @informa @zainul-franciscus-myob and myself. 

So, yeah, happy to help out where we can. Feel free to raise issues and tag us in them!

As for this actual issue. I'm looking to update the version of treat used by this lib. To gain the benefits of this pr [treat/111](https://github.com/seek-oss/treat/pull/111)

I know we have an ident fn [here](https://github.com/maraisr/rollup-plugin-treat/blob/master/lib/index.ts#L216) but I'm not sure if that doing all/some/none of the ident work. Or if we will get the ident fn straight out of treat. 

Ill quickly just raise a PR bumping the version of treat, and then hopefully we can discuss if we need to make changes to index.ts

thanks for the great lib :)

**Comment by maraisr** [comment]
Hey @Blastoplex 

Yeah for sure, I'll add you in as a contributor! This code was legit a weekend project to see if it would work, so definitely needs a coat of paint. So yeah, update what you need! Seeing as its gained some attention, Ill spend some more time on getting it up and rocking. I think there were some holes in it, I'll have to spin it up and remind myself.

In terms of that ident fn, I took that more or less from webpack/treat.

- https://github.com/webpack/loader-utils/blob/master/lib/interpolateName.js#L110-L117
- https://github.com/seek-oss/treat/blob/master/packages/treat/webpack-plugin/loader.js#L82-L90

Like I said; so glad you're using this! Ill get things in order for you, and outline anything missing!

**Comment by Blastoplex** [comment]
I totally get it! This was super use full to us as we don't want to introduce any breaking changes to a system right now. This plugin allows us to transpile with babel, output to cjs + esm with rollup and our dev teams don't need to worry what css in js lib we are using, they just continue to use our output css sheet.

Ill take a look at those functions and pull them into the pr potentially.
